### PR TITLE
Local storage

### PR DESCRIPTION
**Pull request by DominicSimpson**
This was added after I pulled from the main, so rest assured, it's the latest code to which I have added the Local Storage function after this evening's session.

### CODE REVIEW

**Review by LL835 — COMMENTED** [review]
Thanks - really appreciate you adding all this, Dominic.

 - At the moment, it's adding to local storage but not pulling them back into the page on refresh.  This might be fixed if we add lines 10 - 32 in the image into our script.
- We might also need to update our deleteTask function to remove the item from the array so local storage doesn't pull deleted tasks back in. 

Hope that makes sense, and happy to try help with any of this stuff too.

**Comment by LL835** [comment]
Hey team, I've added some code to implement the local storage stuff a bit further. Main changes are:

- deleteTask now also deletes the item from local storage.
- local storage saves the completed status of a task so it remembers if the user has already completed the task.
- lots more comments.

I think it's working ok but please play around and test it some more if you have time!

**Review by georgiaewhitney — COMMENTED** [review]
Hey both - thank you for all your cracking work on this!
I've been playing around with it now and it all seems to work as expected. I haven't been able to force a bug manually, yet. 
The comments are looking very swish - nice work!

**Comment by georgiaewhitney** [comment]
Happy for this to be merged, but appreciate we're doing testing in the bg too.

**Pull request merged**
