### PR TITLE
html css styling

### PR DESCRIPTION
**Pull request by DominicSimpson**
Please have a look and merge to main you're ready.

### CODE REVIEW

**Review by LL835 — COMMENTED** [review]
Thanks for putting this together, Dominic! Looking good. Just a few suggestions if that's ok:

- Make the input field required. 
- Add a `label` (or `aria-label`) to the input for screen readers.
- Instead of having empty elements in `main-container`, leave it completely empty and dynamically add the `flex-container-to-do` divs with js when a user creates a task.
- Change the width of the input from `30vw` to a fixed width so that it doesn't become too small on mobile.

What do we think? Happy to make (some of) these changes so that you're not doing all the work.

**Comment by georgiaewhitney** [comment]
Thank you for getting this together, Dominic - agreed with Derek, looking good! 

Good suggestions, @LL835 - I'm happy to make some of these changes too

**Comment by LL835** [comment]
Ok! Made these changes now and also gave it some extra css for colour. @rockyrelay and @DominicSimpson, feel free to change it.

**Review by georgiaewhitney — APPROVED** [review]
sorry - realised, I just commented - I didn't pull it through the official review. My original comment stands and the styling bits look great!

**Comment by DominicSimpson** [comment]
Thank you so much, Derek - looks very professional now.

**Pull request merged**
